// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: common.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	common.proto
	queries.proto

It has these top-level messages:
	Collection
	Queue
	QueuesCmds
*/
package proto

import fmt "fmt"
import github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
import proto1 "github.com/gogo/protobuf/proto"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import _ "github.com/mwitkow/go-proto-validators"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Collection) Validate() error {
	return nil
}
func (this *Collection_Params) Validate() error {
	if !(this.Limit < 101) {
		return github_com_mwitkow_go_proto_validators.FieldError("Limit", fmt.Errorf(`value '%v' must be less than '101'`, this.Limit))
	}
	return nil
}
func (this *Collection_Info) Validate() error {
	return nil
}
